#Пример использования базы данных
#database:
#  data_type: 'SQLITE'
#  host: ''
#  port: 3306
#  username: ''
#  password: ''
# # Если тип базы данных SQLITE, то указывайте название файла
# # Если тип базы данных MYSQL, то указывайте название таблицы
#  name: 'database'

#Пример использования редис
#redis:
#  host: '127.0.0.1'
#  port: 6379
#  timeout: 3000
#  password: 'password'

items_tag_hider: true

design_display_name: '&7  '